### ISSUE TITLE
Doesn't work out of the box without adding kdyby/console config

### ISSUE THREAD

**Issue by Fuco1** [nette/sandbox#89]
Hi.

Setting up the project as per the readme leaves me with some `kdyby/console` setup errors.

I had to add this to the `app/config/config.neon` to load the homepage

```yml
extensions:
    console: Kdyby\Console\DI\ConsoleExtension

console:
    url: http://app.domain
```
